In [28]:
import math
import numpy
import numpy as np
lcs=numpy.empty(shape=(3, 2), dtype=float)

for i in range(3):
    print("Enter the x-coordinate of line number", i+1, ":")
    lcs[i][0]=float(input())
    print("Enter the y-coordinate of line number", i+1, ":")
    lcs[i][1]=float(input())


mpcs=numpy.empty(2,dtype=float)

mpcs[0]=float(input("Enter the x-coordinate of measuring point : "))
mpcs[1]=float(input("Enter the y-coordinate of measuring point : "))

V = float(input("Enter the rms value of line-to-ground voltage(in kV) :"))
N = int(input("Enter the Number of subconductors in buldle :"))
d = float(input("Enter the diameter of a subconductor in bundle(in meter) :"))
r = float(d/2)
B = float(input("Enter the bundle spacing(in meter) :"))
R = float(B/(2*math.sin(math.pi/N)))
print("R :",R)
S = float(lcs[2][0]-lcs[1][0])
Req = float((N*r*(R**(N-1)))**(1/N))
print("Req :",Req)
H = float(lcs[0][1])
print("H :", H)

D=np.array([0,0,0], dtype=float)

for i in range(3):
    D[i]= float((((mpcs[0]-lcs[i][0])**2)+((mpcs[1]-lcs[i][1])**2))**(1/2))

print(D)
    

D_d=np.array([0,0,0], dtype=float)

for i in range(3):
    D_d[i]= float((((mpcs[0]-lcs[i][0])**2)+((mpcs[1]+lcs[i][1])**2))**(1/2))
    
print(D_d)
    
P=numpy.empty(shape=(3, 3), dtype=float)


for i in range(3):
    for j in range(3):
        if i==j:
            P[i][i]= float(math.log(2*H/Req))
        else:
            P[i][j]= float((1/2)*math.log((((lcs[i][0]-lcs[j][0])**2)+((lcs[i][1]+lcs[j][1])**2))/(((lcs[i][0]-lcs[j][0])**2)+((lcs[i][1]-lcs[j][1])**2))))
            
print(P)

M = np.linalg.inv(P)
print(M)

J=numpy.empty(3,dtype=float)
K=numpy.empty(3,dtype=float)

for i in range(3):
    J[i]= float((mpcs[0]-lcs[i][0])*(((D[i])**(-2))-((D_d[i])**(-2))))
    K[i]= float(((mpcs[1]-lcs[i][1])/((D[i])**2))-((mpcs[1]+lcs[i][1])/((D_d[i])**2)))

print(J)
print(K)

J_h=np.array([0,0,0],dtype=float)
K_v=np.array([0,0,0],dtype=float)

for i in range(3):
    for j in range(3):
        J_h[i] = J_h[i]+(J[j]*M[j][i])
        K_v[i] = K_v[i]+(K[j]*M[j][i])

print(J_h)
print(K_v)

Jh= float(((J_h[0]*J_h[0])+(J_h[1]*J_h[1])+(J_h[2]*J_h[2])-(J_h[0]*J_h[1])-(J_h[1]*J_h[2])-(J_h[2]*J_h[0]))**(1/2))
Kv= float(((K_v[0]*K_v[0])+(K_v[1]*K_v[1])+(K_v[2]*K_v[2])-(K_v[0]*K_v[1])-(K_v[1]*K_v[2])-(K_v[2]*K_v[0]))**(1/2))

print("RMS value of Horizontal component of Electrostatic field : ",Jh*V)
print("RMS value of Vertical component of Electrostatic field : ",Kv*V)

print("RMS value of Total Electrostatic field : ",((((Jh*V)**2)+((Kv*V)**2))**(1/2)))

Enter the x-coordinate of line number 1 :
-12
Enter the y-coordinate of line number 1 :
13
Enter the x-coordinate of line number 2 :
0
Enter the y-coordinate of line number 2 :
13
Enter the x-coordinate of line number 3 :
12
Enter the y-coordinate of line number 3 :
13
Enter the x-coordinate of measuring point : -39
Enter the y-coordinate of measuring point : 0
Enter the rms value of line-to-ground voltage(in kV) :242.487
Enter the Number of subconductors in buldle :2
Enter the diameter of a subconductor in bundle(in meter) :0.0318
Enter the bundle spacing(in meter) :0.4572
R : 0.2286
Req : 0.08526124559259031
H : 13.0
[29.96664813 41.10960958 52.63078947]
[29.96664813 41.10960958 52.63078947]
[[5.7201318  0.86974552 0.38819495]
 [0.86974552 5.7201318  0.86974552]
 [0.38819495 0.86974552 5.7201318 ]]
[[ 0.17933477 -0.02601885 -0.00821433]
 [-0.02601885  0.18273347 -0.02601885]
 [-0.00821433 -0.02601885  0.17933477]]
[-0. -0. -0.]
[-0.02895323 -0.01538462 -0.00938628]
[0. 0. 0.]
[-0.004